from .decompose import decompose_vectorspace_to_namedLC, decompose_vectorspace_onelevel_to_namedLC, NamedLC, IrrepSymbol
from .linear_combination import LinearCombination
from .vectorspace import VectorSpace